import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { PostmortemSection } from '@/components/landing/PostmortemSection';

describe('PostmortemSection Component', () => {
  it('renders eyebrow label, headline, and supporting text correctly', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('04 / POSTMORTEM')).toBeInTheDocument();
    const heading = screen.getByRole('heading', { level: 2 });
    expect(heading).toBeInTheDocument();
    expect(heading.textContent).toMatch(/TURN RESPONSE\s*INTO MEMORY\./i);

    expect(
      screen.getByText(
        /SignalFold transforms the verified incident timeline, impact, decisions, and recovery details into an editable postmortem draft\./i
      )
    ).toBeInTheDocument();
  });

  it('renders technical metadata tags', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('AI DRAFT ONLY')).toBeInTheDocument();
    expect(screen.getByText('HUMAN APPROVED')).toBeInTheDocument();
    expect(screen.getByText('VERSIONED RECORD')).toBeInTheDocument();
  });

  it('renders outer postmortem document preview shell with header and workflow status rail', () => {
    render(<PostmortemSection />);

    // Top Frame Bar
    expect(screen.getByText('SF-2026-0042 / POSTMORTEM')).toBeInTheDocument();
    expect(screen.getByText('HUMAN REVIEW REQUIRED')).toBeInTheDocument();

    // Workflow Status Rail states
    expect(screen.getAllByText('DRAFT').length).toBeGreaterThan(0);
    expect(screen.getByText('IN REVIEW')).toBeInTheDocument();
    expect(screen.getByText('APPROVED')).toBeInTheDocument();
    expect(screen.getByText('PUBLISHED')).toBeInTheDocument();

    // Status indicator label
    expect(screen.getByText('UNAPPROVED RECORD')).toBeInTheDocument();
  });

  it('renders Document Identity block with title, metadata, and pending review status', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('POSTMORTEM DRAFT / 01')).toBeInTheDocument();
    expect(
      screen.getByText('Checkout payments failing after latest deployment')
    ).toBeInTheDocument();

    // Compact metadata
    expect(screen.getByText('INCIDENT')).toBeInTheDocument();
    expect(screen.getAllByText('SF-2026-0042').length).toBeGreaterThan(0);
    expect(screen.getAllByText('SERVICE').length).toBeGreaterThan(0);
    expect(screen.getAllByText('PAYMENTS API').length).toBeGreaterThan(0);
    expect(screen.getByText('SEVERITY')).toBeInTheDocument();
    expect(screen.getByText('SEV1 CRITICAL')).toBeInTheDocument();
    expect(screen.getByText('IMPACT')).toBeInTheDocument();
    expect(screen.getAllByText('37 CUSTOMER REPORTS').length).toBeGreaterThan(0);

    // Review metadata
    expect(screen.getByText('GENERATED BY /')).toBeInTheDocument();
    expect(screen.getAllByText('DEEPSEEK').length).toBeGreaterThan(0);
    expect(screen.getByText('REVIEW STATUS /')).toBeInTheDocument();
    expect(screen.getAllByText('PENDING HUMAN REVIEW').length).toBeGreaterThan(0);
  });

  it('renders Executive Summary section with draft copy and notes', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('01 / EXECUTIVE SUMMARY')).toBeInTheDocument();
    expect(screen.getByText('AI-GENERATED DRAFT')).toBeInTheDocument();
    expect(
      screen.getByText('Editable before review and approval.')
    ).toBeInTheDocument();

    expect(
      screen.getByText(
        /Following the latest deployment, customers were unable to complete card payments through the Payments API\./i
      )
    ).toBeInTheDocument();
  });

  it('renders Customer & Business Impact section with status and structured grid', () => {
    render(<PostmortemSection />);

    expect(
      screen.getByText('02 / CUSTOMER & BUSINESS IMPACT')
    ).toBeInTheDocument();
    expect(screen.getByText('IMPACT REVIEW INCOMPLETE')).toBeInTheDocument();

    expect(
      screen.getByText(
        /Customers were unable to complete card payments through the Payments API during the incident window\./i
      )
    ).toBeInTheDocument();

    // Impact Grid Labels & Values
    expect(screen.getByText('CUSTOMER EFFECT')).toBeInTheDocument();
    expect(screen.getByText('CARD PAYMENTS FAILED')).toBeInTheDocument();

    expect(screen.getByText('KNOWN SCOPE')).toBeInTheDocument();
    expect(screen.getAllByText('37 CUSTOMER REPORTS').length).toBeGreaterThan(0);

    expect(screen.getByText('AFFECTED FLOW')).toBeInTheDocument();
    expect(screen.getByText('CHECKOUT COMPLETION')).toBeInTheDocument();

    expect(screen.getByText('FINANCIAL IMPACT')).toBeInTheDocument();
    expect(screen.getAllByText('PENDING RECONCILIATION').length).toBeGreaterThan(0);

    expect(screen.getByText('CONFIDENCE')).toBeInTheDocument();
    expect(screen.getByText('PARTIAL')).toBeInTheDocument();
    expect(
      screen.getByText('HUMAN VALIDATION REQUIRED')
    ).toBeInTheDocument();
  });

  it('renders Detection section with status, paragraph, and structured grid', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('03 / DETECTION')).toBeInTheDocument();
    expect(
      screen.getByText('DETECTION DETAILS PENDING REVIEW')
    ).toBeInTheDocument();

    expect(
      screen.getByText(
        /The incident was detected through incoming customer and support reports describing failed card payments after the latest deployment\./i
      )
    ).toBeInTheDocument();

    // Detection Grid
    expect(screen.getByText('DETECTION SOURCE')).toBeInTheDocument();
    expect(screen.getByText('INCOMING SUPPORT REPORTS')).toBeInTheDocument();

    expect(screen.getByText('FIRST RECORDED EVENT')).toBeInTheDocument();
    expect(screen.getAllByText('06:14:08').length).toBeGreaterThan(0);

    expect(screen.getByText('PRIMARY SIGNAL')).toBeInTheDocument();
    expect(screen.getByText('CARD PAYMENT FAILURES')).toBeInTheDocument();

    expect(screen.getByText('KNOWN REPORT VOLUME')).toBeInTheDocument();

    expect(screen.getByText('FIRST CUSTOMER IMPACT')).toBeInTheDocument();
    expect(screen.getByText('TIME NOT YET VERIFIED')).toBeInTheDocument();

    expect(screen.getByText('AUTOMATED ALERT')).toBeInTheDocument();
    expect(screen.getAllByText('NOT CONFIRMED').length).toBeGreaterThan(0);

    expect(screen.getAllByText('REVIEW OWNER').length).toBeGreaterThan(0);
    expect(screen.getAllByText('INCIDENT MANAGER').length).toBeGreaterThan(0);
  });

  it('renders Incident Timeline section with chronological events and labels', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('04 / INCIDENT TIMELINE')).toBeInTheDocument();
    expect(
      screen.getByText('VERIFIED EVENTS / RESOLUTION TIME PENDING')
    ).toBeInTheDocument();

    expect(
      screen.getByText(
        /This draft timeline is reconstructed from recorded SignalFold activity\./i
      )
    ).toBeInTheDocument();

    // Event 1
    expect(screen.getAllByText('06:14:08').length).toBeGreaterThan(0);
    expect(screen.getAllByText('SYSTEM').length).toBeGreaterThan(0);
    expect(
      screen.getByText('Incident created from incoming customer reports.')
    ).toBeInTheDocument();

    // Event 2
    expect(screen.getByText('06:15:02')).toBeInTheDocument();
    expect(screen.getAllByText('DEEPSEEK').length).toBeGreaterThan(0);
    expect(screen.getByText('AI SUGGESTION')).toBeInTheDocument();
    expect(
      screen.getByText('AI analysis completed — SEV1 suggested with 94% confidence.')
    ).toBeInTheDocument();

    // Event 3
    expect(screen.getByText('06:16:21')).toBeInTheDocument();
    expect(
      screen.getByText('Accepted severity recommendation: SEV1 / CRITICAL.')
    ).toBeInTheDocument();

    // Event 4
    expect(screen.getByText('06:17:06')).toBeInTheDocument();
    expect(screen.getByText('Assigned as Incident Commander.')).toBeInTheDocument();

    // Event 5
    expect(screen.getByText('06:18:42')).toBeInTheDocument();
    expect(screen.getByText('ALEX RIVERA')).toBeInTheDocument();
    expect(
      screen.getByText('Claimed task: Compare latest deployment changes.')
    ).toBeInTheDocument();

    // Event 6 - Final Pending Milestone
    expect(screen.getByText('TIME PENDING REVIEW')).toBeInTheDocument();
    expect(screen.getByText('SYSTEM RECORD')).toBeInTheDocument();
    expect(screen.getByText('UNVERIFIED MILESTONE')).toBeInTheDocument();
    expect(
      screen.getByText(
        'Service recovery verification and final resolution timestamp require human confirmation.'
      )
    ).toBeInTheDocument();
  });

  it('renders Root Cause section with hypothesis, evidence grid, and status label', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('05 / ROOT CAUSE')).toBeInTheDocument();
    expect(
      screen.getByText('WORKING HYPOTHESIS / NOT CONFIRMED')
    ).toBeInTheDocument();

    expect(
      screen.getByText(
        /The available incident evidence indicates that the payment failures began after the latest deployment/i
      )
    ).toBeInTheDocument();

    // Evidence Grid
    expect(screen.getByText('CURRENT HYPOTHESIS')).toBeInTheDocument();
    expect(screen.getByText('DEPLOYMENT-RELATED REGRESSION')).toBeInTheDocument();

    expect(screen.getByText('CONFIRMATION STATUS')).toBeInTheDocument();
    expect(screen.getAllByText(/NOT CONFIRMED/).length).toBeGreaterThan(0);

    expect(screen.getByText('AFFECTED COMPONENT')).toBeInTheDocument();
    expect(screen.getAllByText('PAYMENTS API').length).toBeGreaterThan(0);

    expect(screen.getByText('LIKELY CHANGE WINDOW')).toBeInTheDocument();
    expect(screen.getByText('LATEST DEPLOYMENT')).toBeInTheDocument();

    expect(screen.getByText('SUPPORTING EVIDENCE')).toBeInTheDocument();
    expect(screen.getByText('FAILURES REPORTED AFTER DEPLOYMENT')).toBeInTheDocument();

    expect(screen.getByText('MISSING EVIDENCE')).toBeInTheDocument();
    expect(screen.getByText('EXACT CHANGE NOT IDENTIFIED')).toBeInTheDocument();

    expect(screen.getByText('VALIDATION REQUIRED')).toBeInTheDocument();
    expect(screen.getByText('CODE AND CONFIGURATION REVIEW')).toBeInTheDocument();

    expect(screen.getAllByText('REVIEW OWNER').length).toBeGreaterThan(0);
    expect(screen.getByText('INCIDENT MANAGER + ENGINEERING')).toBeInTheDocument();

    expect(
      screen.getByText(
        'This hypothesis must remain editable until supporting technical evidence is attached and reviewed.'
      )
    ).toBeInTheDocument();
  });

  it('renders Contributing Factors section with structured rows and human validation status', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('06 / CONTRIBUTING FACTORS')).toBeInTheDocument();
    expect(
      screen.getByText('CANDIDATE FACTORS / HUMAN VALIDATION REQUIRED')
    ).toBeInTheDocument();

    expect(
      screen.getByText(
        /The following factors may have increased the incident’s impact or delayed confident diagnosis/i
      )
    ).toBeInTheDocument();

    // Four factors
    expect(screen.getAllByText('CUSTOMER-LED DETECTION').length).toBeGreaterThan(0);
    expect(screen.getByText('PARTIALLY VERIFIED')).toBeInTheDocument();

    expect(screen.getAllByText('CHANGE SCOPE NOT YET ISOLATED').length).toBeGreaterThan(0);
    expect(screen.getAllByText('OPEN INVESTIGATION').length).toBeGreaterThan(0);

    expect(screen.getByText('IMPACT START TIME UNKNOWN')).toBeInTheDocument();
    expect(screen.getAllByText('TIME UNVERIFIED').length).toBeGreaterThan(0);

    expect(screen.getByText('FINANCIAL IMPACT UNRECONCILED')).toBeInTheDocument();
    expect(screen.getAllByText('PENDING RECONCILIATION').length).toBeGreaterThan(0);
  });

  it('renders Resolution section with status, copy, compact grid, and checklist', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('07 / RESOLUTION')).toBeInTheDocument();
    expect(screen.getAllByText('RECOVERY VERIFICATION PENDING').length).toBeGreaterThan(0);

    expect(
      screen.getByText(
        /The response team coordinated investigation and recovery tasks for the Payments API incident/i
      )
    ).toBeInTheDocument();

    // Compact grid labels and values
    expect(screen.getByText('CURRENT INCIDENT STATE')).toBeInTheDocument();
    expect(screen.getByText('INVESTIGATING')).toBeInTheDocument();
    expect(screen.getByText('RECOVERY ACTION')).toBeInTheDocument();
    expect(screen.getAllByText('NOT YET VERIFIED').length).toBeGreaterThan(0);
    expect(screen.getByText('SERVICE RECOVERY')).toBeInTheDocument();
    expect(screen.getByText('CONFIRMATION REQUIRED')).toBeInTheDocument();
    expect(screen.getByText('RESOLUTION TIME')).toBeInTheDocument();
    expect(screen.getAllByText('PENDING HUMAN REVIEW').length).toBeGreaterThan(0);
    expect(screen.getByText('CRITICAL TASK REVIEW')).toBeInTheDocument();
    expect(screen.getByText('OPEN ITEMS REQUIRE REVIEW')).toBeInTheDocument();
    expect(screen.getByText('ROOT CAUSE STATUS')).toBeInTheDocument();
    expect(screen.getByText('UNKNOWN / NOT CONFIRMED')).toBeInTheDocument();
    expect(screen.getByText('REMAINING RISK')).toBeInTheDocument();
    expect(screen.getByText('NOT YET DOCUMENTED')).toBeInTheDocument();
    expect(screen.getByText('APPROVAL OWNER')).toBeInTheDocument();

    // Checklist
    expect(screen.getByText('Resolution summary confirmed')).toBeInTheDocument();
    expect(screen.getByText('Service recovery verified')).toBeInTheDocument();
    expect(screen.getByText('Remaining risk documented')).toBeInTheDocument();
    expect(screen.getByText('Open critical tasks reviewed')).toBeInTheDocument();
    expect(screen.getByText('Final resolution timestamp confirmed')).toBeInTheDocument();

    // Closing note
    expect(
      screen.getByText(
        /This incident must not be marked resolved until recovery evidence and required resolution fields are reviewed by an authorized human/i
      )
    ).toBeInTheDocument();
  });

  it('renders What Went Well section with status, intro copy, rows and evidence indicators', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('08 / WHAT WENT WELL')).toBeInTheDocument();
    expect(screen.getByText('DRAFT OBSERVATIONS / HUMAN REVIEW REQUIRED')).toBeInTheDocument();

    expect(
      screen.getByText(
        /The recorded SignalFold activity shows several response practices that supported clear coordination/i
      )
    ).toBeInTheDocument();

    // Verify row headers
    expect(screen.getByText('SIGNALS WERE CONSOLIDATED')).toBeInTheDocument();
    expect(screen.getByText('AI REMAINED ADVISORY')).toBeInTheDocument();
    expect(screen.getByText('OWNERSHIP WAS RECORDED')).toBeInTheDocument();
    expect(screen.getByText('IMPORTANT ACTIONS WERE TRACEABLE')).toBeInTheDocument();

    // Verify observations
    expect(screen.getByText('Incoming customer and support reports were converted into one structured incident record.')).toBeInTheDocument();
    expect(screen.getByText('AI analysis provided a severity suggestion without automatically changing the incident.')).toBeInTheDocument();
    expect(screen.getByText('The response timeline clearly recorded incident command and task ownership.')).toBeInTheDocument();
    expect(screen.getByText('Recorded timestamps and actors made the early response sequence reconstructable.')).toBeInTheDocument();

    // Verify evidences
    expect(screen.getByText('Incident SF-2026-0042 was created from the reported payment failures.')).toBeInTheDocument();
    expect(screen.getByText('DeepSeek suggested SEV1 with 94% confidence, and Maya Chen explicitly accepted the recommendation.')).toBeInTheDocument();
    expect(screen.getByText('Maya Chen was assigned as Incident Commander, and Alex Rivera claimed the deployment review task.')).toBeInTheDocument();
    expect(screen.getByText('The timeline includes incident creation, AI analysis, severity acceptance, commander assignment, and task claim events.')).toBeInTheDocument();
  });

  it('renders What Went Poorly section with status, intro copy, rows and indicators', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('09 / WHAT WENT POORLY')).toBeInTheDocument();
    expect(screen.getByText('DRAFT GAPS / HUMAN REVIEW REQUIRED')).toBeInTheDocument();

    expect(
      screen.getByText(
        /The current incident record reveals several gaps that limited early certainty and left important recovery details incomplete/i
      )
    ).toBeInTheDocument();

    // Verify row headers
    expect(screen.getAllByText('DETECTION DEPENDED ON CUSTOMER REPORTS').length).toBeGreaterThan(0);
    expect(screen.getAllByText('CHANGE SCOPE WAS NOT ISOLATED').length).toBeGreaterThan(0);
    expect(screen.getAllByText('CUSTOMER AND FINANCIAL IMPACT REMAIN INCOMPLETE').length).toBeGreaterThan(0);
    expect(screen.getAllByText('RECOVERY EVIDENCE IS NOT YET COMPLETE').length).toBeGreaterThan(0);

    // Verify gaps
    expect(screen.getByText('The earliest confirmed signals came from incoming customer and support reports.')).toBeInTheDocument();
    expect(screen.getByText('The response record does not yet identify the exact code, configuration, or dependency change associated with the failures.')).toBeInTheDocument();
    expect(screen.getByText('Thirty-seven customer reports are known, but the full number of affected transactions and final financial impact have not been reconciled.')).toBeInTheDocument();
    expect(screen.getByText('The document does not yet contain a verified recovery action, restoration time, remaining risk, or final resolution timestamp.')).toBeInTheDocument();

    // Verify review requirements
    expect(screen.getByText('Verify whether monitoring detected the payment failures before customer reports arrived.')).toBeInTheDocument();
    expect(screen.getByText('Compare deployment changes and attach technical evidence before confirming root cause.')).toBeInTheDocument();
    expect(screen.getByText('Reconcile payment records and confirmed customer impact.')).toBeInTheDocument();
    expect(screen.getByText('Confirm recovery evidence and required resolution fields before changing incident status.')).toBeInTheDocument();

    // Verify row statuses
    expect(screen.getByText('MONITORING EVIDENCE MISSING')).toBeInTheDocument();
    expect(screen.getAllByText('OPEN INVESTIGATION').length).toBeGreaterThan(0);
    expect(screen.getAllByText('PENDING RECONCILIATION').length).toBeGreaterThan(0);
    expect(screen.getAllByText('RECOVERY VERIFICATION PENDING').length).toBeGreaterThan(0);
  });

  it('renders Preventive Actions section with status, intro, proposed rows, priority and actions', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('10 / PREVENTIVE ACTIONS')).toBeInTheDocument();
    expect(screen.getByText('DRAFT ACTION PLAN / HUMAN APPROVAL REQUIRED')).toBeInTheDocument();

    expect(
      screen.getByText(
        /The following preventive actions respond to gaps identified in the current incident record/i
      )
    ).toBeInTheDocument();

    // Verify row titles
    expect(screen.getByText('IMPROVE PAYMENT FAILURE DETECTION')).toBeInTheDocument();
    expect(screen.getByText('ISOLATE DEPLOYMENT CHANGE SCOPE')).toBeInTheDocument();
    expect(screen.getByText('STANDARDIZE RECOVERY VERIFICATION')).toBeInTheDocument();

    // Verify proposed actions
    expect(screen.getByText('Define and validate automated detection coverage for repeated card-payment failures affecting the Payments API.')).toBeInTheDocument();
    expect(screen.getByText('Create a repeatable review process for comparing payment-service deployments against incident symptoms and affected components.')).toBeInTheDocument();
    expect(screen.getByText('Establish a documented reconciliation step for failed payment attempts, confirmed customer impact, and final financial exposure.')).toBeInTheDocument();
    expect(screen.getByText('Require recovery evidence, remaining-risk documentation, critical-task review, and a confirmed resolution timestamp before an incident may be resolved.')).toBeInTheDocument();

    // Verify addresses gaps
    expect(screen.getAllByText('CUSTOMER-LED DETECTION').length).toBeGreaterThan(0);
    expect(screen.getAllByText('CHANGE SCOPE NOT YET ISOLATED').length).toBeGreaterThan(0);
    expect(screen.getAllByText('CUSTOMER AND FINANCIAL IMPACT REMAIN INCOMPLETE').length).toBeGreaterThan(0);
    expect(screen.getAllByText('RECOVERY EVIDENCE IS NOT YET COMPLETE').length).toBeGreaterThan(0);

    // Verify evidences
    expect(screen.getByText('Documented alert criteria, validation results, and confirmed incident-routing behavior.')).toBeInTheDocument();
    expect(screen.getByText('Linked deployment changes, technical findings, and an evidence-backed conclusion.')).toBeInTheDocument();
    expect(screen.getByText('Reviewed payment records and a human-confirmed impact summary.')).toBeInTheDocument();
    expect(screen.getByText('Completed resolution checklist and authorized human confirmation.')).toBeInTheDocument();

    // Priorities
    expect(screen.getAllByText('HIGH').length).toBeGreaterThan(0);
    expect(screen.getByText('MEDIUM')).toBeInTheDocument();
    expect(screen.getByText('CRITICAL')).toBeInTheDocument();

    // Statuses
    expect(screen.getAllByText('PROPOSED / NOT APPROVED').length).toBeGreaterThan(0);
  });

  it('renders Owners and Due Dates section with header status, intro, table columns and values', () => {
    render(<PostmortemSection />);

    expect(screen.getByText('11 / OWNERS & DUE DATES')).toBeInTheDocument();
    expect(screen.getByText('ASSIGNMENT REQUIRED BEFORE APPROVAL')).toBeInTheDocument();

    expect(
      screen.getByText(
        /Follow-up ownership and due dates have not yet been approved/i
      )
    ).toBeInTheDocument();

    // Verify table headings / rows
    expect(screen.getAllByText('PAYMENTS API SERVICE OWNER').length).toBeGreaterThan(0);
    expect(screen.getAllByText('ENGINEERING LEAD').length).toBeGreaterThan(0);
    expect(screen.getAllByText('INCIDENT MANAGER + BUSINESS OPERATIONS').length).toBeGreaterThan(0);
    expect(screen.getAllByText('INCIDENT MANAGER').length).toBeGreaterThan(0);

    expect(screen.getAllByText('ROLE PROPOSAL').length).toBeGreaterThan(0);
    expect(screen.getAllByText('SHARED ROLE PROPOSAL').length).toBeGreaterThan(0);
    expect(screen.getAllByText('NOT ASSIGNED').length).toBeGreaterThan(0);
    expect(screen.getAllByText('OWNER CONFIRMATION REQUIRED').length).toBeGreaterThan(0);

    // Closing note
    expect(
      screen.getByText(
        /Preventive actions must not be marked approved until every item has a confirmed owner, due date, and acceptance evidence/i
      )
    ).toBeInTheDocument();

    // Footer update
    expect(screen.getByText('DRAFT CONTENT COMPLETE / HUMAN REVIEW REQUIRED')).toBeInTheDocument();
  });

  it('has id="postmortem" and scroll-mt-20 for anchor navigation from navbar', () => {
    const { container } = render(<PostmortemSection />);
    const section = container.querySelector('section#postmortem');
    expect(section).toBeInTheDocument();
    expect(section?.classList.contains('scroll-mt-20')).toBe(true);

    const stickyColumn = container.querySelector('.postmortemEditorialSticky');
    expect(stickyColumn).toBeInTheDocument();
  });
});
