import { getBase44Client } from '@/integrations/base44/client';
import { getBase44RuntimeConfig } from '@/integrations/base44/config';
import type { DashboardOverview } from '@/features/dashboard/domain/dashboardTypes';
import type { Incident, IncidentCreateInput, IncidentFilters, IncidentUpdate } from '@/features/incidents/domain/incidentTypes';
import type { Service, ServiceInput } from '@/features/services/domain/serviceTypes';
import type { IncidentReadModel, OperationalGateway } from '../ports/OperationalGateway';

const unwrap = (value: unknown): unknown => value && typeof value === 'object' && 'data' in value ? (value as { data: unknown }).data : value;
const invoke = async (name: string, input: Record<string, unknown>) => { const client = getBase44Client(getBase44RuntimeConfig()); if (!client) throw new Error('SERVICE_UNAVAILABLE'); return unwrap(await client.functions.invoke(name as never, input)) as Record<string, unknown>; };
export const projectService = (r: Record<string, unknown>): Service => ({ id: String(r.id), organizationId: String(r.organization_id), name: String(r.name), slug: String(r.slug), description: typeof r.description === 'string' ? r.description : undefined, criticality: r.criticality as Service['criticality'], operationalStatus: r.operational_status as Service['operationalStatus'], ownerUserId: typeof r.owner_user_id === 'string' ? r.owner_user_id : undefined, tags: Array.isArray(r.tags) ? r.tags.map(String) : [], isActive: r.is_active === true, isDemo: r.is_demo === true, createdAt: typeof r.created_date === 'string' ? r.created_date : undefined, updatedAt: typeof r.updated_date === 'string' ? r.updated_date : undefined });
export const projectIncident = (r: Record<string, unknown>): Incident => ({ id: String(r.id), organizationId: String(r.organization_id), code: String(r.code), title: String(r.title), description: String(r.description), source: r.source as Incident['source'], serviceId: typeof r.service_id === 'string' ? r.service_id : undefined, reporterUserId: String(r.reporter_user_id), commanderUserId: typeof r.commander_user_id === 'string' ? r.commander_user_id : undefined, severity: r.severity as Incident['severity'], severitySource: r.severity_source as Incident['severitySource'], status: r.status as Incident['status'], impactSummary: typeof r.impact_summary === 'string' ? r.impact_summary : undefined, observedStartAt: typeof r.observed_start_at === 'string' ? r.observed_start_at : undefined, reportedAt: String(r.reported_at), acknowledgedAt: typeof r.acknowledged_at === 'string' ? r.acknowledged_at : undefined, resolvedAt: typeof r.resolved_at === 'string' ? r.resolved_at : undefined, closedAt: typeof r.closed_at === 'string' ? r.closed_at : undefined, recoveryVerified: r.recovery_verified === true, publicVisibility: r.public_visibility as Incident['publicVisibility'], isDemo: r.is_demo === true, reopenedCount: Number(r.reopened_count ?? 0), createdAt: typeof r.created_date === 'string' ? r.created_date : undefined, updatedAt: typeof r.updated_date === 'string' ? r.updated_date : undefined });
const projectUpdate = (r: Record<string, unknown>): IncidentUpdate => ({ id: String(r.id), organizationId: String(r.organization_id), incidentId: String(r.incident_id), eventType: String(r.event_type), actorUserId: typeof r.actor_user_id === 'string' ? r.actor_user_id : undefined, actorType: r.actor_type as IncidentUpdate['actorType'], visibility: r.visibility as IncidentUpdate['visibility'], message: String(r.message), occurredAt: String(r.occurred_at), isDemo: r.is_demo === true });

export class Base44OperationalGateway implements OperationalGateway {
  async listServices(organizationId: string, includeInactive = false) { const r = await invoke('list-services', { organizationId, includeInactive }); return ((r.services ?? []) as Record<string, unknown>[]).map(projectService); }
  async createService(organizationId: string, input: ServiceInput) { return projectService((await invoke('create-service', { organizationId, ...input })).service as Record<string, unknown>); }
  async updateService(organizationId: string, serviceId: string, input: Partial<ServiceInput> & { isActive?: boolean; requestId: string }) { return projectService((await invoke('update-service', { organizationId, serviceId, ...input })).service as Record<string, unknown>); }
  async listIncidents(organizationId: string, filters: IncidentFilters = {}) { const r = await invoke('list-incidents', { organizationId, ...filters }); return { incidents: ((r.incidents ?? []) as Record<string, unknown>[]).map(projectIncident), nextCursor: typeof r.nextCursor === 'string' ? r.nextCursor : null }; }
  async getIncident(organizationId: string, incidentId: string): Promise<IncidentReadModel> { const r = await invoke('get-incident', { organizationId, incidentId }); return { incident: projectIncident(r.incident as Record<string, unknown>), service: r.service ? projectService(r.service as Record<string, unknown>) : null, updates: ((r.updates ?? []) as Record<string, unknown>[]).map(projectUpdate) }; }
  async createIncident(organizationId: string, input: IncidentCreateInput) { return projectIncident((await invoke('create-incident', { organizationId, ...input })).incident as Record<string, unknown>); }
  async getDashboardOverview(organizationId: string) { return (await invoke('get-dashboard-overview', { organizationId })) as unknown as DashboardOverview; }
  async seedDemoData(organizationId: string, requestId: string) { return (await invoke('seed-demo-data', { sourceOrganizationId: organizationId, confirmation: 'CREATE DEMO WORKSPACE', requestId })) as { organizationId: string; created: number }; }
  async resetDemoData(organizationId: string, requestId: string) { return (await invoke('reset-demo-data', { organizationId, confirmation: 'RESET DEMO DATA', requestId })) as { deleted: number }; }
}
