import { getBase44Client } from '@/integrations/base44/client';
import type { Base44RuntimeConfig } from '@/integrations/base44/config';
import type { OrganizationGateway, OnboardingInput, OrganizationResolution } from '../ports/OrganizationGateway';
import type { SafeOrganizationMember } from '../domain/organizationTypes';
import type { ActiveOrganizationContext, Organization, Membership } from '../domain/organizationTypes';
const unwrap = (value: unknown): unknown => value && typeof value === 'object' && 'data' in value ? (value as { data: unknown }).data : value;
type OrganizationFunctionName = 'complete-organization-onboarding' | 'resolve-organization-context' | 'select-active-organization' | 'list-organization-members';
const invoke = async (config: Base44RuntimeConfig, name: OrganizationFunctionName, input?: Record<string, unknown>): Promise<unknown> => { const client = getBase44Client(config); if (!client) throw new Error('SERVICE_UNAVAILABLE'); return unwrap(await client.functions.invoke(name, input)); };
const projectOrganization = (raw: Record<string, unknown>): Organization => ({ id: String(raw.id), name: String(raw.name), slug: String(raw.slug), logoUrl: typeof raw.logo_url === 'string' ? raw.logo_url : undefined, defaultTimezone: String(raw.default_timezone), incidentPrefix: String(raw.incident_prefix), publicStatusEnabled: raw.public_status_enabled === true, createdByUserId: String(raw.created_by_user_id), isDemo: raw.is_demo === true });
const projectMembership = (raw: Record<string, unknown>): Membership => ({ id: String(raw.id), organizationId: String(raw.organization_id), userId: String(raw.user_id), role: raw.role as Membership['role'], status: raw.status as Membership['status'], invitedByUserId: typeof raw.invited_by_user_id === 'string' ? raw.invited_by_user_id : undefined, joinedAt: typeof raw.joined_at === 'string' ? raw.joined_at : undefined, displayTitle: typeof raw.display_title === 'string' ? raw.display_title : undefined });
const projectContext = (raw: Record<string, unknown>): ActiveOrganizationContext | null => raw.organization && raw.membership ? { organization: projectOrganization(raw.organization as Record<string, unknown>), membership: projectMembership(raw.membership as Record<string, unknown>) } : null;
const normalizeResolution = (raw: Record<string, unknown>): OrganizationResolution => ({ state: raw.state as OrganizationResolution['state'], context: projectContext(raw), selectable: Array.isArray(raw.selectable) ? raw.selectable.map((item) => projectContext(item as Record<string, unknown>)).filter((item): item is ActiveOrganizationContext => item !== null) : [] });
export class Base44OrganizationGateway implements OrganizationGateway { constructor(private readonly config: Base44RuntimeConfig) {} async resolveCurrentOrganizationContext() { return normalizeResolution(await invoke(this.config, 'resolve-organization-context') as Record<string, unknown>); } async completeOrganizationOnboarding(input: OnboardingInput) { return normalizeResolution(await invoke(this.config, 'complete-organization-onboarding', input) as Record<string, unknown>); } async selectActiveOrganization(organizationId: string) { return normalizeResolution(await invoke(this.config, 'select-active-organization', { organizationId }) as Record<string, unknown>); } async listActiveOrganizationMembers() { const result = await invoke(this.config, 'list-organization-members') as { members?: SafeOrganizationMember[] }; return result.members ?? []; } }
