import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { useAuth } from '@/features/auth/AuthProvider';
import { getOrganizationGateway } from './organizationGateway';
import type { ActiveOrganizationContext, OrganizationAccessState, SafeOrganizationMember } from './domain/organizationTypes';
import type { OnboardingInput, OrganizationResolution } from './ports/OrganizationGateway';
type Value = { state: OrganizationAccessState; context: ActiveOrganizationContext | null; members: SafeOrganizationMember[]; isMockMode: boolean; error: string | null; resolve: () => Promise<void>; refreshMembers: () => Promise<void>; completeOnboarding: (input: OnboardingInput) => Promise<boolean>; selectActiveOrganization: (id: string) => Promise<boolean> };
const mockContext: ActiveOrganizationContext = { organization: { id: 'mock-northstar', name: 'NORTHSTAR COMMERCE', slug: 'northstar-commerce', defaultTimezone: 'UTC', incidentPrefix: 'SF', publicStatusEnabled: false, createdByUserId: 'mock-user', isDemo: true }, membership: { id: 'mock-membership', organizationId: 'mock-northstar', userId: 'mock-user', role: 'admin', status: 'active' } };
const fallback: Value = { state: 'UNRESOLVED', context: null, members: [], isMockMode: true, error: null, resolve: async () => undefined, refreshMembers: async () => undefined, completeOnboarding: async () => false, selectActiveOrganization: async () => false };
const Context = createContext<Value>(fallback);
export function OrganizationProvider({ children }: { children: ReactNode }) { const auth = useAuth(); const gateway = useMemo(() => getOrganizationGateway(), [auth.isMockMode]); const [value, setValue] = useState<Value>({ ...fallback, isMockMode: auth.isMockMode, state: auth.isMockMode ? 'ACTIVE' : 'UNRESOLVED', context: auth.isMockMode ? mockContext : null }); const pending = useRef<Promise<void> | null>(null); const identity = auth.user?.id ?? null;
 const resolve = useCallback(async () => { if (auth.state.status !== 'AUTHENTICATED' && !auth.isMockMode) return; if (pending.current) return pending.current; setValue(v => ({ ...v, state: 'RESOLVING', error: null })); const p = gateway.resolveCurrentOrganizationContext().then(r => setValue(v => ({ ...v, state: r.state, context: r.context, error: null }))).catch(() => setValue(v => ({ ...v, state: 'ERROR', context: null, error: 'ORGANIZATION CONTEXT UNAVAILABLE' }))).finally(() => { pending.current = null; }); pending.current = p; return p; }, [auth.isMockMode, auth.state.status, gateway]);
 useEffect(() => { if (auth.isMockMode) return; setValue(v => ({ ...v, isMockMode: false, context: null, members: [], state: 'UNRESOLVED' })); if (identity !== null) void resolve(); }, [identity, auth.isMockMode, resolve]);
 const completeOnboarding = useCallback(async (input: OnboardingInput) => { try { const r = await gateway.completeOrganizationOnboarding(input); setValue(v => ({ ...v, state: r.state, context: r.context, error: null })); return r.state === 'ACTIVE'; } catch { setValue(v => ({ ...v, state: 'ERROR', error: 'ORGANIZATION SETUP UNAVAILABLE' })); return false; } }, [gateway]);
 const selectActiveOrganization = useCallback(async (id: string) => { try { const r = await gateway.selectActiveOrganization(id); setValue(v => ({ ...v, state: r.state, context: r.context, error: null })); return r.state === 'ACTIVE'; } catch { setValue(v => ({ ...v, state: 'ERROR', error: 'ORGANIZATION SELECTION UNAVAILABLE' })); return false; } }, [gateway]);
 const refreshMembers = useCallback(async () => { try { const result = await gateway.listActiveOrganizationMembers(); setValue(v => ({ ...v, members: result })); } catch { setValue(v => ({ ...v, error: 'MEMBERSHIP DIRECTORY UNAVAILABLE' })); } }, [gateway]);
 const output = useMemo(() => ({ ...value, resolve, refreshMembers, completeOnboarding, selectActiveOrganization }), [value, resolve, refreshMembers, completeOnboarding, selectActiveOrganization]); return <Context.Provider value={output}>{children}</Context.Provider>; }
export function useOrganization() { return useContext(Context); }
