import type { ReactNode } from 'react';
import { useOrganization } from './OrganizationProvider';
import { useEffect } from 'react';
import { canRole } from './domain/capabilities';

export function Base44TeamBoundary() {
  const { context, isMockMode, members, refreshMembers } = useOrganization();
  useEffect(() => { if (!isMockMode && context) void refreshMembers(); }, [context, isMockMode, refreshMembers]);
  if (isMockMode) return null;
  return <div className="space-y-6 w-full max-w-7xl mx-auto"><div className="pb-6 border-b border-[#242522]"><div className="text-[9px] font-mono font-bold tracking-widest text-[#5C5E58] uppercase">{context?.organization.name ?? 'ORGANIZATION' } / MEMBERSHIP DIRECTORY</div><h2 className="text-3xl font-extrabold tracking-tight text-[#F3F1EA] uppercase" style={{ fontFamily: 'var(--font-display)' }}>TEAM & MEMBERSHIP</h2><p className="text-sm text-[#A8AAA3] max-w-[640px] leading-relaxed">Active members for the current organization. Membership role and status are authoritative.</p></div><div className="border border-[#242522] bg-[#141513]/40 p-4 space-y-3"><div className="text-[9px] font-mono tracking-widest text-[#5C5E58] uppercase">ACTIVE ORGANIZATION MEMBERS</div>{members.length === 0 ? <div className="text-sm text-[#A8AAA3]">No membership records are available.</div> : members.map((member) => <div key={member.membershipId} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#242522] py-3"><div><div className="font-semibold text-[#F3F1EA]">{member.displayName ?? member.email ?? member.userId}</div><div className="text-xs text-[#A8AAA3]">{member.displayTitle ?? 'No title provided'}</div></div><div className="text-right text-xs font-mono uppercase"><div className="text-[#D6FF3F]">{member.role.replace('_', ' ')}</div><div className="text-[#A8AAA3]">{member.status}</div></div></div>)}</div></div>;
}

export function Base44SettingsBoundary() {
  const { context, isMockMode } = useOrganization();
  if (isMockMode) return null;
  const admin = context ? canRole(context.membership.role, 'MANAGE_ORGANIZATION_SETTINGS') : false;
  return <div className="space-y-6 w-full max-w-7xl mx-auto"><div className="pb-6 border-b border-[#242522]"><div className="text-[9px] font-mono font-bold tracking-widest text-[#5C5E58] uppercase">{context?.organization.name ?? 'ORGANIZATION'} / SETTINGS</div><h2 className="text-3xl font-extrabold tracking-tight text-[#F3F1EA] uppercase" style={{ fontFamily: 'var(--font-display)' }}>WORKSPACE SETTINGS</h2><p className="text-sm text-[#A8AAA3] max-w-[640px] leading-relaxed">Authoritative organization values for the active workspace.</p></div><dl className="grid grid-cols-1 sm:grid-cols-2 gap-4">{[['ORGANIZATION NAME', context?.organization.name], ['SLUG', context?.organization.slug], ['TIMEZONE', context?.organization.defaultTimezone], ['INCIDENT PREFIX', context?.organization.incidentPrefix], ['PUBLIC STATUS', context?.organization.publicStatusEnabled ? 'ENABLED' : 'DISABLED'], ['AUTHORITY', admin ? 'ORGANIZATION ADMIN' : context?.membership.role.replace('_', ' ').toUpperCase()]].map(([label, value]) => <div key={label} className="border border-[#242522] bg-[#141513]/40 p-4"><dt className="text-[9px] font-mono tracking-widest text-[#5C5E58]">{label}</dt><dd className="mt-2 text-sm font-mono font-bold text-[#F3F1EA]">{value ?? 'NOT AVAILABLE'}</dd></div>)}</dl></div>;
}

export function Base44EmptyBoundary({ title, children }: { title: string; children?: ReactNode }) { const { isMockMode } = useOrganization(); if (isMockMode) return null; return <section data-testid="base44-empty-state-wrapper" className="min-h-[420px] w-full min-w-0 flex items-center justify-center px-0 sm:px-4" style={{ display: 'flex', width: '100%', minWidth: 0, justifyContent: 'center', writingMode: 'horizontal-tb' }}><div data-testid="base44-empty-state-card" className="w-full min-w-0 max-w-2xl border border-[#242522] bg-[#141513]/40 p-6 sm:p-8" style={{ display: 'block', width: '100%', minWidth: 0, maxWidth: '42rem', boxSizing: 'border-box', writingMode: 'horizontal-tb' }}><div data-testid="base44-empty-state-content" style={{ display: 'block', width: '100%', minWidth: 0, textAlign: 'center', writingMode: 'horizontal-tb' }}><div className="text-xs font-mono tracking-widest text-[#D6FF3F]" style={{ display: 'block', width: '100%', minWidth: 0, writingMode: 'horizontal-tb', wordBreak: 'normal', overflowWrap: 'normal', whiteSpace: 'normal' }}>{title}</div><p data-testid="base44-empty-state-description" className="text-sm text-[#A8AAA3] leading-relaxed" style={{ display: 'block', width: '100%', maxWidth: '36rem', minWidth: 0, marginInline: 'auto', whiteSpace: 'normal', wordBreak: 'normal', overflowWrap: 'normal', writingMode: 'horizontal-tb' }}>{children ?? 'No organization records are available yet.'}</p></div></div></section>; }
